version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo Build step - nothing to build in static HTML.
artifacts:
  files:
    - '**/*'
